name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libglib2.0-dev \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev

      - name: Install dependencies
        run: npm ci

      - name: Check TypeScript
        run: npm run build

      - name: Check Rust
        run: |
          cd src-tauri
          cargo check
          cargo clippy -- -D warnings

      - name: Run tests (if available)
        run: npm test || echo "No tests configured yet"

      - name: Check formatting
        run: |
          npm run lint || echo "No linting configured yet"
          npx prettier --check . || echo "No prettier configured yet"
